pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      request_reviews:
        users: [bpholt]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.13.7, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.13.7, adopt@1.11)
      - status-success=Build and Test (ubuntu-latest, 2.12.15, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.12.15, adopt@1.11)
      - status-success=Build and Test (ubuntu-latest, 3.0.2, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 3.0.2, adopt@1.11)
    actions:
      merge:
        method: squash
        strict: true
